on:
  push:
jobs:
  test:
    name: Test matrix colon text
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
        - text: "contains a : colon"
        - text: "doesn't contain a colon"
    steps:
      - run: |
          echo "Text: ${{ matrix.text }}"
