on:
  push:
jobs:
  test:
    name: Test conda create
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
        - env: jax-jaxlib
          deps: "abc"
        - env: jaxlib-jax
          deps: "def"
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
      - run: conda info
        shell: bash -l {0}
      - run: conda list
        shell: bash -l {0}
      - run: conda env list
        shell: bash -l {0}
