on:
  push: { branches: [ main ] }
jobs:
  test:
    name: Test matrix colon text
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
        - text: "job param contains a : colon"
        - text: "job param doesn't contain a colon"
        - text: "another job with a : colon"
        - text: "another job without a colon"
    steps:
      - run: |
          echo "Text: ${{ matrix.text }}"
