on:
  push:
jobs:
  test:
    name: Test `conda create`
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - env: jax-jaxlib
          deps: conda-forge::jax conda-forge::jaxlib
        - env: jaxlib-jax
          deps: conda-forge::jaxlib conda-forge::jax
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda info
        shell: bash -l {0}
      - run: conda list
        shell: bash -l {0}
      - run: conda env list
        shell: bash -l {0}
      - run: conda create -n ${{ matrix.env }} -d ${{ matrix.deps }}
        shell: bash -l {0}
