on:
  push:
jobs:
  test:
    name: Test `conda create`
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        solver: [ default, mamba ]
        deps: [ "jax jaxlib", "jaxlib jax" ]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda info
        shell: bash -l {0}
      - run: conda list
        shell: bash -l {0}
      - run: conda env list
        shell: bash -l {0}
      - name: Maybe install and configure libmamba solver
        if: matrix.solver == 'mamba'
        run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
        shell: bash -l {0}
      - run: conda config --get solver
        shell: bash -l {0}
      - run: conda create -n jax-test -d -c conda-forge ${{ matrix.deps }}
        shell: bash -l {0}
